create table m_permission
(
    id               bigint generated by default as identity
        primary key,
    created_by       varchar(255),
    created_date     timestamp(6),
    identifier       varchar(255),
    internal_id      varchar(255)
        constraint ukcaw4o6ih2utmy7ns2mopiaghx
            unique,
    name             varchar(255),
    notes            varchar(255),
    public_id        uuid not null
        constraint uk674ogi6revpatlnoqqhdqdroe
            unique,
    reserved_field_1 varchar(255),
    reserved_field_2 varchar(255),
    reserved_field_3 varchar(255),
    reserved_field_4 timestamp(6),
    reserved_field_5 text,
    type             varchar(255),
    update_by        varchar(255),
    update_date      timestamp(6),
    role_internal_id varchar(255)
        constraint fkmsmycmcty3nf9l8xbewncplp2
            references m_role (internal_id)
);

alter table m_permission
    owner to postgres;