create table m_user
(
    id               bigint generated by default as identity
        primary key,
    created_by       varchar(255),
    created_date     timestamp(6),
    email            varchar(255)
        constraint ukrycw44p7cruupkosx3ibmj9q3
            unique,
    first_name       varchar(255),
    internal_id      varchar(255)
        constraint ukoj24htsmjkcggt5qj5vhgdg3v
            unique,
    last_name        varchar(255),
    phone            varchar(255)
        constraint uk74lxcl4brqh72rle4t89ktf76
            unique,
    public_id        uuid not null
        constraint uk13xuoq9nelklxb8e30jyltvey
            unique,
    reserved_field_1 varchar(255),
    reserved_field_2 varchar(255),
    reserved_field_3 varchar(255),
    reserved_field_4 timestamp(6),
    reserved_field_5 text,
    update_by        varchar(255),
    update_date      timestamp(6),
    role_internal_id varchar(255)
        constraint fkin5jtktjst2xk4nxas9wh02ju
            references m_role (internal_id),
    username         varchar(255),
    birth_date       date,
    id_card_number   varchar(255)
        constraint uk1ogk6e4dxot4u6klfoq4q0xwt
            unique,
    profile_picture  varchar(255),
    status           boolean
);

alter table m_user
    owner to postgres;
