create table t_user_session
(
    id                bigint generated by default as identity
        primary key,
    created_by        varchar(255),
    created_date      timestamp(6),
    internal_id       varchar(255)
        constraint uk5nwl0jsa4e8cnoe4gqsw84si3
            unique,
    is_active         boolean,
    last_activity     timestamp(6),
    public_id         uuid not null
        constraint uklqmc8eei6nbw7c3kod9afqdwd
            unique,
    reserved_field_1  varchar(255),
    reserved_field_10 text,
    reserved_field_2  varchar(255),
    reserved_field_3  varchar(255),
    reserved_field_4  timestamp(6),
    reserved_field_5  timestamp(6),
    reserved_field_6  varchar(255),
    reserved_field_7  varchar(255),
    reserved_field_8  varchar(255),
    reserved_field_9  varchar(255),
    session_id        varchar(255),
    update_by         varchar(255),
    update_date       timestamp(6),
    user_internal_id  varchar(255)
        constraint fkajwdjbwykmvuy86vpne5ttf55
            references m_user (internal_id)
);

alter table t_user_session
    owner to postgres;