create table t_user_auth
(
    id                  bigint generated by default as identity
        primary key,
    authentication_type varchar(255),
    biometric_template  varchar(255),
    created_by          varchar(255),
    created_date        timestamp(6),
    internal_id         varchar(255)
        constraint ukj4piee95f2gndh94b7ixvy5bu
            unique,
    password            varchar(255),
    pin                 varchar(255),
    public_id           uuid not null
        constraint uk2todu9s89qq8icfuqxij63xh
            unique,
    reserved_field_1    varchar(255),
    reserved_field_10   text,
    reserved_field_2    varchar(255),
    reserved_field_3    varchar(255),
    reserved_field_4    timestamp(6),
    reserved_field_5    timestamp(6),
    reserved_field_6    varchar(255),
    reserved_field_7    varchar(255),
    reserved_field_8    varchar(255),
    reserved_field_9    varchar(255),
    term_condition      boolean,
    update_by           varchar(255),
    update_date         timestamp(6),
    username            varchar(255),
    user_internal_id    varchar(255)
        constraint fk2yor61k5obyveie0t9qwsgftj
            references m_user (internal_id)
);

alter table t_user_auth
    owner to postgres;